frontend/src/App.tsx
frontend/src/pages/Sumin.tsx

[FE/feat/#22] 테스트 페이지 추가

---

frontend/src/App.tsx
frontend/src/pages/Testing.tsx

[FE/feat/#21] 테스트

---

docker-compose.yml

feat: compose implement

---

Backend/package.json
docker-compose.yml

compose 파일 build ./backend -> ./Backend 코드 수정
Closes #이슈 번호

chore : compose 경로 수정

---

docker-compose.yml

fix: 자동배포 버그 수정

---

Backend/swagger/swagger.js

chore: swagger host 수정

---

Backend/swagger/swagger.js

// sawgger url : http://43.202.208.226:3000/api-docs/
// sawgger url : http://localhost:3000/api-docs/
Closes #이슈 번호

[BE/feat/#36] Swagger 접속 명령어 작성

---

docker-compose-dev.yml

Be/feat/#48 포트번호 충돌 해결

---

Backend/app.js

test: 젠킨스 dev 스웨거 동작 확인 및 자동배포 테스트
Closes #이슈 번호

[BE/feat/#48] test: 젠킨스 dev 스웨거 동작 확인 및 자동배포 테스트

---

Backend/swagger/swagger_output.json

feat: swagger Base URL 수정
Closes #이슈 번호

[BE/feat/#48] Swagger Base URL 수정

---

Backend/package.json

package.json에
"cors": "^2.8.5", 추가
(이렇게 하는거 맞는지 모르겠음................)
Closes #59

[BE/feat/#59] cors 관련 package.json 수정

---

Backend/app.js

app.use(cors());
모두 접근 가능하게 허용
Closes #59

[BE/feat/#59] cors 모두 허용

---

Backend/app.js
Backend/swagger/swagger_output.json

[BE/fix/#66: cors

---

Backend/app.js
Backend/swagger/swagger.js

[Be/fix/#66] CORS dev 테스트
Closes #이슈 번호

[Be/fix/#66] CORS dev 테스트

---

Backend/swagger/swagger.js
Backend/swagger/swagger_output.json

[Be/fix/#66] CORS -> Swagger port Test
Closes #68

[BE/fix/#66] CORS -> Swagger port Test

---

Backend/app.js
Backend/routes/test/secreatsManager.js
Backend/routes/test/test.js
Backend/swagger/swagger_output.json

[BE/feat/#75] SecretsManager Test Router 추가
Closes #75

[BE/feat/#75] SecretsManager Test Router 추가

---

Backend/app.js
Backend/mysql/configDB.js
Backend/mysql/database.js
Backend/mysql/database.json
Backend/package-lock.json
Backend/package.json
Backend/routes/mypage.js
Backend/routes/result.js
Backend/routes/tarot.js
Backend/routes/test/secreatsManager.js
Backend/routes/test/test.js
Backend/routes/user.js
Backend/swagger/swagger.js
Backend/swagger/swagger_output.json
docker-compose-dev.yml

[Be/feat/#78] DB 연동 & 스웨거 정리 & 스켈레톤 코드 구현 & 주석 추가
Closes #78

[Be/feat/#78] DB 연동 & 스웨거 정리 & 스켈레톤 코드 구현 & 주석 추가

---

Backend/chatgpt/api.js

fix: bug fix

---

Backend/routes/tarot.js
Backend/swagger/swagger_output.json

- 운 카테고리 Table에서 가이드라인 내용 조회
- 뽑은 카드 Table에 뽑은 카드 정보 저장(gpt 프롬프팅 완료 후 수정 계획)
Closes #99

[BE/feat/#99] 가이드라인 내용 조회, 뽑은 카드 저장

---

frontend/src/App.tsx
frontend/src/component/Navbar.tsx
frontend/src/pages/Signup.tsx

[Fe/feat/#93] 회원가입 페이지 퍼블리싱

---

Backend/routes/tarot.js
Backend/swagger/swagger_output.json

- 사용자 id와 파트너 id를 입력받아 poll을 생성하는 기능 구현
- TODO : 예외 반환 형식 처리
Closes #이슈 번호

[BE/feat/#102]: Poll APi Implement

---

frontend/src/App.tsx
frontend/src/pages/CardSave.tsx

[FE/feat/#98] 카드 저장 페이지 퍼블리싱

---

Backend/swagger/swagger_output.json

chore: swagger update

---

Backend/app.js
Backend/aws/awsS3.js
Backend/package-lock.json
Backend/package.json
Backend/routes/tarot.js
Backend/swagger/swagger_output.json

[BE/feat/#111] S3 filename order

---

Backend/aws/awsS3.js
Backend/package-lock.json
Backend/routes/tarot.js
Backend/swagger/swagger_output.json

[BE/feat/#118] s3 이미지 정보에 대한 api 추가

---

frontend/src/pages/TarotProcess.tsx

[FE/feat/#107] 타로 진행 페이지 반응형 처리

---

Backend/routes/tarot.js
Backend/swagger/swagger_output.json

- 요청값 운 종류, 뽑는 사람 수 로 변경
- 운 카테고리 table에 record insert 후 테스트
Closes #122

feat : 가이드라인 불러오기 API 수정(요청값 수정)

---

Backend/routes/user.js
Backend/swagger/swagger_output.json

회원가입, 로그인, 로그아웃, 토큰 유저 기능 구현
Closes #91

[BE/feat/#91] 유저 로직 구현

---

Backend/package-lock.json
Backend/package.json

build jsonwebtoken install
Closes #

[BE/feat/#91] build jsonwebtoken install

---

Backend/app.js
Backend/routes/user.js
Backend/swagger/swagger_output.json

[BE/feat/#91]스웨거 쿼리로 변경

---

frontend/src/pages/BeforeChat.tsx
frontend/src/pages/CardSave.tsx
frontend/src/pages/Landing.tsx
frontend/src/pages/TarotProcess.tsx

[FE/design/#110] 프론트 디자인 반응형 처리

---

Backend/routes/result.js
Backend/routes/tarot.js
Backend/swagger/swagger_output.json

[BE/feat/#127] gpt api result json

---

Backend/swagger/swagger_output.json

[BE/feat/#131] swagger conflict 버그를 수정했어요

---

Backend/routes/mypage.js
Backend/routes/result.js
Backend/routes/tarot.js
Backend/routes/user.js
Backend/swagger/swagger_output.json

로 결과 상세조회 구현 및 파일 정리
Closes #136

[Be/feat/#136] 타로 결과 상세조회 구현 및 파일 정리

---

Backend/routes/result.js
Backend/swagger/swagger_output.json

[Be/refactor/#139] develop 최신화

---

Backend/routes/result.js
Backend/swagger/swagger_output.json

[BE/feat/#134] swagger bug

---

Backend/routes/result.js
Backend/routes/tarot.js
Backend/swagger/swagger_output.json

- 가이드라인 API 오타 수정 : gide -> guide
- 종합 저장 API 기능 구현 :  타로 결과 저장, 뽑은 카드 정보 저장
Closes #142

[Be/feat/#142] 종합 저장 API 기능 구현

---

Backend/routes/user.js
Backend/swagger/swagger_output.json

swagger error message 출력
Closes #

[BE/feat/#91]swagger error message 출력

---

Backend/routes/mypage.js
Backend/swagger/swagger_output.json

Mypage '/detail' Swagger 개선
Closes #145

[BE/refactor/#145] Mypage '/detail' Swagger 개선

---

Backend/routes/result.js
Backend/swagger/swagger_output.json

- 요청값 누락 체크
- 뽑은 카드 정보 여러장 받기
- 뽑은 카드 정보 여러장 저장
Closes #151

[BE/fix/#151] 종합 결과 저장 API 수정

---

Backend/app.js
Backend/middleware/verifyToken.js
Backend/routes/mypage.js
Backend/routes/token.js
Backend/routes/user.js
Backend/swagger/swagger.js
Backend/swagger/swagger_output.json

1. JWT 검증
2. Refresh Token 재발급
3. JWT로 사용자 추출하기
4. Swagger 개선
Closes #이슈 번호

[Be/refactor/#145] JWT 및 Swagger 개선

---

Backend/routes/user.js
Backend/swagger/swagger.js
Backend/swagger/swagger_output.json

[BE/refactor/#157] swagger 오류 수정

---

frontend/src/pages/Login.tsx
frontend/src/pages/Signup.tsx

로그인, 회원가입 페이지 반응형, 비밀번호 숨기기
Closes #149

[FE/design/#149] 로그인, 회원가입 페이지 반응형, 비밀번호 숨기기

---

Backend/swagger/swagger_output.json

[BE/fix/#162]: token 검증 수정

---

Backend/chatgpt/api.js
Backend/routes/test/test.js
Backend/swagger/swagger_output.json

[BE/feat/#167] gpt json 형태로 test 구현

---

Backend/routes/result.js
Backend/swagger/swagger_output.json

- 누락 여부 체크 수정
- poll_id 요청 방법 query -> body
- 등등.. 됐으면 좋겠다.. 제발..
Closes #168

refactor : 종합 결과 및 뽑은 카드 정보 저장 API 수정

---

Backend/routes/result.js
Backend/swagger/swagger_output.json

- erd 변경에 따른 result.js 쿼리문 및 테이블 관련 객체 이름 수정
Closes #173

refactor : erd 변경에 따른 result.js 수정

---

Backend/routes/tarot.js
Backend/swagger/swagger.js
Backend/swagger/swagger_output.json

[BE/refactor#172] 수정된 DB -> tarot.js 반영
Closes #172

[BE/refactor#172] 수정된 DB -> tarot.js 반영

---

Backend/routes/mypage.js
Backend/routes/user.js
Backend/swagger/swagger_output.json

[BE/refactor/#178] 리팩토리 완료

---

frontend/src/App.tsx
frontend/src/pages/Login.tsx
frontend/src/pages/Signup.tsx

로그인, 회원가입 페이지 rem 변환
Closes #177

[FE/design/#177] 로그인, 회원가입 페이지 rem 변환

---

Backend/routes/mypage.js
Backend/routes/result.js
Backend/routes/user.js
Backend/swagger/swagger.js
Backend/swagger/swagger_output.json

[BE/refactor/#172] refactoring

---

Backend/routes/user.js
Backend/swagger/swagger_output.json

fix: 토큰 버그 수정

---

frontend/src/App.tsx
frontend/src/pages/CardSelect.tsx
frontend/src/pages/FortuneSelect.tsx
frontend/src/pages/Landing.tsx
frontend/src/pages/TarotProcess.tsx

[FE/design/#183] 반응형 디자인 처리

---

frontend/src/pages/FortuneSelect.tsx
frontend/src/pages/MyPage.tsx
frontend/src/pages/TarotProcess.tsx

폰트 문제 및 운선택 페이지 디자인 수정
Closes #이슈 번호

[FE/design/#182] 폰트 문제 및 운선택 페이지 디자인 수정을 등록한다.

---

Backend/routes/mypage.js
Backend/routes/user.js
Backend/swagger/swagger.js
Backend/swagger/swagger_output.json

2024-01-13 02:33 버그내용 수정
- 유효하지 않는 토큰 에러 수정
- refresh토큰 저장되지 않는 버그 수정
- mypage 버그 수정
Closes #이슈 번호

fix: 01-13 02:34 버그 수정

---

Backend/routes/mypage.js

fix: mypage/delete 10진수 추가
Closes #이슈 번호

fix: mypage/delete 10진수 추가

---

docker-compose-dev.yml
frontend/Dockerfile
frontend/package.json
frontend/src/pages/CardSave.tsx
frontend/vite.config.ts

Front Docker Setting
Closes #이슈 번호

feat: Front Docker Setting

---

Backend/routes/mypage.js
Backend/routes/user.js
Backend/swagger/swagger.js
Backend/swagger/swagger_output.json

- Swagger Request Header에 JWT 토큰 입력 삭제 후 로그인 상태 JWT만 추출하도록 수정
- Mypage -> detail & delete에서 poll Id를 찾을 수 없는 경우 서버가 멈추는 현상 발생(타입 에러 등)으로 result Null 체크로 해결
Closes #이슈 번호

[BE/feat/#201] mypage result Null Check

---

Backend/routes/tarot.js
Backend/swagger/swagger_output.json

가이드라인 API 스웨거 
- luckOpt description, example 수정
폴 아이디 생성 API
- token에서 user_id 추출 후 poll_id 생성
Closes #203

refactor : tarot.js 가이드라인 API 스웨거 수정, 폴 아이디 생성 API 수정

---

Backend/middleware/commonResponse.js
Backend/middleware/verifyToken.js
Backend/routes/mypage.js
Backend/swagger/swagger.js
Backend/swagger/swagger_output.json

[Be/feat/#201] Swagger 문서 업데이트

---

Backend/routes/tarot.js

- commonResponse 미들웨어 연결
Closes #206

[BE/refactor/#206] tarot.js commonResponse 미들웨어 연결 수정

---

Backend/app.js
Backend/routes/mypage.js
Backend/routes/tarot.js
Backend/swagger/swagger.js
Backend/swagger/swagger_output.json

refactor: Swagger 개선
Closes #이슈 번호

[BE/feat/#210] refactor: Swagger 개선

---

Backend/routes/result.js
Backend/swagger/swagger_output.json

refactoring swagger.responses[200] in result.js + 달러표시 제거
Closes #204

[BE/refactor/#204] refactoring swagger.responses[200] in result.js

---

Backend/routes/mypage.js
Backend/routes/user.js
Backend/swagger/swagger_output.json

refactor: 에러관련 swagger 주석수정
Closes #215

[BE/refactor/#215] refactor: 에러관련 swagger 주석수정

---

Backend/routes/mypage.js
Backend/routes/result.js
Backend/swagger/swagger_output.json

result/save car 누락일 경우 에러 처리
Closes #이슈 번호

[BE/refactor/#214]  result/save car 누락일 경우 에러 처리

---

Backend/routes/poll.js
Backend/routes/tarot.js
Backend/swagger/swagger_output.json

tarot.js 스웨거 오류 메시지 수정
Closes #218

[BE/refactor/#218] update tarot.js swagger error message

---

backend/routes/stream.js
backend/swagger/swagger.js
backend/swagger/swagger_output.json

fix: stream fuc error

---

backend/card/toCardVaild.js
backend/routes/stream.js

[BE/feat/#232] card 폴더 위치 수정

---

backend/routes/tarot.js
backend/swagger/swagger_output.json

- 오류 에러 처리를 비동기 방식으로 수정
Closes #이슈 번호

[BE/refactor/#234] tarot.js 오류 -> 비동기 수정

---

backend/routes/tarot.js

- db connection 빼먹어서 추가^__^..
- 그 외 겹치는 오류 메시지 수정.. 등..
Closes #234

[BE/refactor/#234] tarot.js 오류 처리 수정

---

backend/aws/awsS3.js
backend/routes/stream.js
backend/routes/tarot.js

refactor : AWS S3 카드 정보 조회

---

docker-compose-dev.yml
nginx/Dockerfile
nginx/nginx.conf

fix: server_name 수정
Closes #이슈 번호

[BE/fix/#246] server_name 수정

---

nginx/Dockerfile

[BE/fix/#246] 파일 경로 수정
Closes #이슈 번호

[BE/fix/#246] 파일 경로 수정

---

docker-compose-dev.yml

[BE/fix#246] 파일 경로 수정

---

frontend/package-lock.json
frontend/package.json
frontend/src/pages/Friendship.tsx
frontend/src/pages/LoveFortune.tsx
frontend/src/pages/MoneyFortune.tsx
frontend/src/pages/TodayFortune.tsx
frontend/src/pages/WishFortune.tsx
frontend/vite.config.ts

[Fe/feat/#237] 가이드라인 페이지 API 연동

---

backend/middleware/socketConnection.js

[BE/feat/#262]: stream userId 버그 수정 완료

---

backend/app.js
backend/routes/mypage.js
backend/routes/stream.js
backend/swagger/swagger_output.json

etc: stream api 유저 id 요구 제거

---

frontend/src/component/Navbar.tsx

[FE/feat/#271] 로그아웃 기능 구현을 등록한다

---

backend/app.js

fix: socket cors error

---

backend/routes/stream.js

[BE/feat/#280] undefined 추가 문제 해결

---

backend/routes/poll.js
backend/swagger/swagger.js
backend/swagger/swagger_output.json

[BE/feat#282]: 마이페이지 결과 리스트 조회 TODO: ERR_HTTP_HEADERS_SENT

---

nginx/nginx.conf

[BE/fix/#290]: nginx.conf 443 추가
Closes #이슈 번호

[BE/fix/#290]: nginx.conf 443 추가

---

nginx/Dockerfile

nginx.conf 443 추가
Closes #이슈 번호

[BE/fix/#290] nginx.conf 443 추가

---

init-letsencrypt.sh

init.sh 환경변수  추가
Closes #이슈 번호

[BE/fix#290] init.sh 환경변수  추가

---

nginx/nginx.conf

nginx.conf 443 삭제
Closes #이슈 번호

BE/fix#290] nginx.conf 443 삭제

---

nginx/nginx.conf

[BE/fix/#290] 443 포트 열기~

---

nginx/nginx.conf

[BE/fix/#290] nginx.conf 수정

---

init-letsencrypt.sh

init.sh -> reload 주석
Closes #이슈 번호

[BE/fix/#290] init.sh -> reload 주석

---

docker-compose-dev.yml

[BE/fix/#290] 인증서 재발급 restart 임시 비활성화
Closes #이슈 번호

[BE/fix/#290] 인증서 재발급 restart 임시 비활성화

---

docker-compose-dev.yml

[BE/fix/#290] Nginx volumes 경로 수정
Closes #이슈 번호

[BE/fix/#290] Nginx volumes 경로 수정

---

nginx/nginx.conf

Nginx.conf -> ssl 관련 경로 주석 처리
Closes #이슈 번호

[BE/fix/#290] Nginx.conf -> ssl 관련 경로 주석 처리

---

certbot/logs/letsencrypt.log
certbot/logs/letsencrypt.log.1
certbot/logs/letsencrypt.log.10
certbot/logs/letsencrypt.log.11
certbot/logs/letsencrypt.log.2
certbot/logs/letsencrypt.log.3
certbot/logs/letsencrypt.log.4
certbot/logs/letsencrypt.log.5
certbot/logs/letsencrypt.log.6
certbot/logs/letsencrypt.log.7
certbot/logs/letsencrypt.log.8
certbot/logs/letsencrypt.log.9
docker-compose-dev.yml
nginx/nginx.conf

[Be/fix/#290] feat: tairot.online 접속
Closes #이슈 번호

[Be/fix/#290] feat: tairot.online 접속

---

backend/routes/token.js

fix: token

---

docker-compose-dev.yml
init-letsencrypt.sh
nginx/nginx.conf

test: 인증서 발급 테스트
Closes #이슈 번호

test: 인증서 발급 테스트

---

docker-compose-dev.yml
init-letsencrypt.sh

[BE/fix/#290] test: https 테스트
Closes #이슈 번호

[BE/fix/#290] test: https 테스트

---

docker-compose-dev.yml
nginx/nginx.conf

[BE/fix/#290] test: https 테스트 (진짜 된다)
Closes #이슈 번호

[BE/fix/#290] test: https 테스트 (진짜 된다)

---

init-letsencrypt.sh

[Update] init-letsencrypt.sh -> 젠킨스 자동실행 로직 변경
Closes #이슈 번호

[Update] init-letsencrypt.sh -> 젠킨스 자동실행 로직 변경

---

init-letsencrypt.sh

[BE/test]: init sh 수정
Closes #이슈 번호

[BE/test]: init sh 수정

---

docker-compose-dev.yml
init-letsencrypt.sh

[Be/fix/#290] 성공기원 feat#1
Closes #이슈 번호

[Be/fix/#290] 성공기원 feat#1

---

backend/routes/poll.js

fix: ERR_HTTP_HEADERS_SENT
Closes #이슈 번호

[BE/fix/#282] ERR_HTTP_HEADERS_SENT

---

backend/routes/stream.js

[BE/fix/#322] json으로 문자열을 보내던 오류를 수정하였습니다.

---

docker-compose-dev.yml

- [ x] 💯 테스트는 잘 통과했나요?
- [ x] 🏗️ 빌드는 성공했나요?
- [ x] 🧹 불필요한 코드는 제거했나요?
- [ x] 💭 이슈는 등록했나요?
- [ x] 🏷️ 라벨은 등록했나요?
- [ x] 🌈 알록달록한가요?
Closes #이슈 번호

fix: https 구현

---

docker-compose-dev.yml

[BEfix#321]  볼륨 마운팅 오류 테스트
Closes #이슈 번호

[BEfix#321]  볼륨 마운팅 오류 테스트

---

docker-compose-dev.yml

[BE/fix#321] 볼륨 마운팅 오류 테스트
Closes #이슈 번호

[BE/fix#321] 볼륨 마운팅 오류 테스트

---

docker-compose-dev.yml
nginx/nginx.conf

fix: ngnix 환경 변수

---

nginx/nginx.conf

fix: ngnix 설정

---

nginx/nginx.conf

[BE/feat/#335] 오류 수정

---

nginx/nginx.conf

fix: ngnix

---

nginx/nginx.conf

feat: https

---

nginx/nginx.conf

요청 제한 및 프록시 설정 추가
Closes #이슈 번호

[BE/feat/#348] ngnix 무한 요청 방지 및 프론트, 백엔드 설정 추가

---

nginx/nginx.conf

[BE/fix/#350] : https 내부 연결

---

nginx/nginx.conf

[BE/fix#352]: https 오타

---

backend/routes/poll.js
backend/swagger/swagger.js
backend/swagger/swagger_output.json

[BE/chore]#354] poll 리스트에서 poll_id  GET
Closes #이슈 번호

[BE/chore]#354] poll 리스트에서 poll_id  GET

---

backend/routes/poll.js
backend/routes/tarot.js
backend/swagger/swagger_output.json

swagger -> poll/list 부분 파라미터 Integer로 수정
Closes #358

[BE/fix/#358]: 스웨거 수정

---

docker-compose-dev.yml

[BE/fix#258] 도커 컴포즈 경로 수정
Closes #이슈 번호

[BE/fix#258] 도커 컴포즈 경로 수정

---

docker-compose-dev.yml

[BE/fix/#258] 중꺽마 모니터링 (살짝 꺽임)
Closes #이슈 번호

[BE/fix/#258] 중꺽마 모니터링 (살짝 꺽임)

---

docker-compose-dev.yml
prometheus/Dockerfile

[BE/fix/#258] 중꺽마 모니터링 (반 꺽임) 
Closes #이슈 번호

[BE/fix/#258] 중꺽마 모니터링 (반 꺽임) 

---

docker-compose-dev.yml

[BE/feat/#258] prometheus Implement
Closes #이슈 번호

[BE/feat/#258] prometheus Implement

---

docker-compose-dev.yml

[BE/fix#258] Prometheus bolumes 수정
Closes #이슈 번호

[BE/fix#258] Prometheus bolumes 수정

---

frontend/src/component/Navbar.tsx
frontend/src/pages/CardSave.tsx
frontend/src/pages/CardSelect.tsx
frontend/src/pages/FortuneSelect.tsx
frontend/src/pages/Friendship.tsx
frontend/src/pages/LoveFortune.tsx
frontend/src/pages/MoneyFortune.tsx
frontend/src/pages/TodayFortune.tsx
frontend/src/pages/WishFortune.tsx

- Navbar 좌우 간격 조절
- 배경이미지 margin: auto
- 운세 채팅방 titlebox, titlecontent 수정
Todayfortune.tsx의 titlebox, titlecontent에서 필요한 부분 수정 후 복사해서 나머지 ~fortune.tsx에 붙여넣기 했으니 코드 리뷰 때 참고 바람,,
적용 후 로컬에서 돌렸을 때 이상한 점은 발견 안됨
Closes #376

[FE/refactor/#376] 배경이미지, 채팅페이지 title 관련 수정

---

docker-compose-dev.yml

[BE/fix#258] 볼륨 수정( 한번만 걸려라.)
Closes #이슈 번호

[BE/fix#258] 볼륨 수정( 한번만 걸려라.)

---

backend/routes/poll.js
backend/routes/tarot.js
backend/swagger/swagger.js
backend/swagger/swagger_output.json

[BE/feat/#383] Share Detail Implement
Closes #이슈 번호

[BE/feat/#383] Share Detail Implement

---

frontend/.eslintrc.cjs
frontend/.gitignore
frontend/index.html
frontend/package-lock.json
frontend/package.json
frontend/src/App.tsx
frontend/src/component/Modal.tsx
frontend/src/pages/CardSave.tsx
frontend/src/pages/Friendship.tsx
frontend/src/pages/LoveFortune.tsx
frontend/src/pages/MoneyFortune.tsx
frontend/src/pages/ResultDetail.tsx
frontend/src/pages/ResultShare.tsx
frontend/src/pages/TarotProcess.tsx
frontend/src/pages/TodayFortune.tsx
frontend/src/pages/WishFortune.tsx
frontend/src/state/atom.ts
frontend/src/utils/shareKakaoLink.ts
frontend/src/utils/uploadImgur.ts

가이드라인 로직 수정 및 공유하기 저장하기 기능 추가
Closes #373

[FE/feat/#373] 가이드라인 로직 수정 및 공유하기 저장하기 기능 추가

---

frontend/package-lock.json
frontend/package.json
frontend/src/pages/Login.tsx
frontend/src/pages/Signup.tsx

로그인, 회원가입 Swal  모달창 수정
Closes #393

[FE/desgin/#393]로그인, 회원가입 Swal  모달창 수정

---

nginx/nginx.conf

소켓 테스트 및 기타 테스트를 위한 변경 사항
Closes #이슈 번호

[BE/chore/#397] 백엔드 포트 3000 -> 3001 임시 변경

---

nginx/nginx.conf

chore: change api address

---

frontend/src/assets/font-S-CoreDream-3Light.css
frontend/src/pages/FortuneSelect.tsx

FortuneSelect.tsx 수정
- 운 카테고리 안내 글 수정
- 운 카테고리 페이지 전체 글꼴 수정
- 운 카테고리 카드 뒷면 내용 수정
font import할 css 파일 2개 추가
- font-S-CoreDream-3Light.css
- font-Universe-B.css
Closes #404

[FE/design/#404] FortuneSelect.tsx 수정, font import할 css 파일 2개 추가

---

backend/swagger/swagger.js
nginx/nginx.conf

feat: 기존 가능으로

---

docker-compose-dev.yml
nginx/nginx.conf

fix:  주소 문제

---

docker-compose-dev.yml

fix: 주소 추가

---

docker-compose-dev.yml

Reverts 2023-winter-techeer-sw-bootcamp-TeamF/TeamF#414

Revert "fix: 주소 추가"

---

frontend/src/assets/font-YUniverse-B.css

font-YUniverse-B.css 추가
Closes #404

[FE/design/#404] font-YUniverse-B.css 추가

---

backend/app.js

fix app.js

---

backend/swagger/swagger_output.json

fix:swagger

---

backend/swagger/swagger.js
backend/swagger/swagger_output.json

fix: swagger

---

frontend/src/component/Navbar.tsx

navbar logout login 좌우 간격 통일
Closes #436

[FE/design/#436] navbar logout margin 수정

---

backend/mysql/database.js

[BE/feat] 이모지 구현
Closes #이슈 번호

[BE/feat] 이모지 구현

---

backend/app.js
backend/appConfig.js
backend/chatgpt/streamJson.js
backend/repository/mysqlPromptRepository.js
backend/routes/tarot.js
backend/service/promptService.js

[BE/feat/#444] mysql에서 프롬프트를 불러오도록 했어요!

---

nginx/nginx.conf

[Be/feat/#450] socket 설정 nginx에 추가

---

backend/routes/polls.js
backend/swagger/swagger.js
backend/swagger/swagger_output.json

[BE/feat/#451] poll List DESC
Closes #이슈 번호

[BE/feat/#451] poll List DESC

---

backend/routes/polls.js
backend/swagger/swagger.js
backend/swagger/swagger_output.json

[BE/feat/#455] 결과 상세보기 날짜 추가
Closes #이슈 번호

[BE/feat/#455] 결과 상세보기 날짜 추가

---

backend/swagger/swagger.js

Main Swagger 포트 변경
Closes #이슈 번호

Main Swagger 포트 변경

---

backend/swagger/swagger_output.json

Main swagger.out 포트 변경
Closes #이슈 번호

Main swagger.out 포트 변경

---

docker-compose-main.yml

docker-compose-main.yml 오타 수정
Closes #이슈 번호

docker-compose-main.yml 오타 수정

---

backend/bases/cardsQuery.js
backend/bases/resultQuery.js
backend/routes/share.js
backend/swagger/swagger.js
backend/swagger/swagger_output.json
package-lock.json

SRP 리팩토링 share.js 완료
Closes #464

[Be/refactor/#441]: SRP 리팩토링 share.js 완료

---

frontend/src/App.tsx
frontend/src/component/Navbar.tsx
frontend/src/pages/CardSave.tsx
frontend/src/pages/CardSelect.tsx
frontend/src/pages/FortuneSelect.tsx
frontend/src/pages/Friendship.tsx
frontend/src/pages/LoveFortune.tsx
frontend/src/pages/MoneyFortune.tsx
frontend/src/pages/MyPage.tsx
frontend/src/pages/ResultDetail.tsx
frontend/src/pages/TarotProcess.tsx
frontend/src/pages/TarotProcess1.tsx
frontend/src/pages/TarotProcess5.tsx
frontend/src/pages/TodayFortune.tsx
frontend/src/pages/WishFortune.tsx

[FE/design/#443] 전체적인 디자인 css 수정

---

backend/appConfig.js
backend/card/toCardVaild.js
backend/chatgpt/message.js
backend/chatgpt/streamJson.js
backend/repository/mysqlLuckListRepository.js
backend/repository/mysqlPromptRepository.js
backend/routes/tarot.js
backend/service/luckListService.js

fix: tarot result 오류 수정

---

backend/routes/polls.js
backend/swagger/swagger_output.json

[BE/feat#468] swagger 수정 (미안합니다 프론트)
Closes #468

[BE/feat#468] swagger 수정 (미안합니다 프론트)

---

backend/bases/cardsQuery.js
backend/bases/resultQuery.js
backend/bases/searchQuery.js
backend/routes/polls.js
backend/swagger/swagger_output.json

[BE/refactor/#472] SRP 리팩토링 2차 수정

---

backend/routes/tarot.js

[BE/fix/#480]: 오늘의 운세 저장 버그를 고쳤어요

---

frontend/src/component/Navbar.tsx
frontend/src/pages/Friendship.tsx
frontend/src/pages/LoveFortune.tsx
frontend/src/pages/MoneyFortune.tsx
frontend/src/pages/TodayFortune.tsx
frontend/src/pages/WishFortune.tsx

타로마스터와의 대화 디자인 수정 완료
Closes #이슈 번호

[FE/design/#484타로마스터와의 대화 디자인 수정 완료]

---

frontend/src/pages/CardSave.tsx
frontend/src/pages/Friendship.tsx
frontend/src/pages/Login.tsx
frontend/src/pages/LoveFortune.tsx
frontend/src/pages/MoneyFortune.tsx
frontend/src/pages/MyPage.tsx
frontend/src/pages/TodayFortune.tsx
frontend/src/pages/WishFortune.tsx

[FE/design/#484] 글꼴수정완료

---

backend/swagger/swagger_output.json

[BE/fix/#485] 젠킨스 공지 테스트
Closes #이슈 번호

[BE/fix/#485] 젠킨스 공지 테스트
